### ISSUE TITLE
error in "MegaCore minimal setup" graph

### ISSUE THREAD

**Issue by wothke** [MCUdude/MegaCore#10]
From what I see VCC pins are 52+21 and GND pins are 53+22. The two 100nF capacitor related comments therefore refer to the wrong pins, e.g. "Place as close to pin 20 and 21 as possible" should read "Place as close to pin 21 and 22 as possible", etc,_

**Comment by MCUdude** [comment]
You're right, I'll fix it right away. Thanks!
