### ISSUE TITLE
Feature-Req: compatible Megacore-Variant

### ISSUE THREAD

**Issue by MarphXL** [MCUdude/MegaCore#100]
[pins_arduino.h.txt](https://github.com/MCUdude/MegaCore/files/2718379/pins_arduino.h.txt)

For compatibilityreasons I needed a megacore-variant of mega2560 with all pin's and interrupts and made a new variant the megaplus. perhaps you want to integrate it:

**Comment by MCUdude** [comment]
MegaCore already have this Arduino MEGA 2560 extended pinout. It's just not available through the boards manager yet. All that's left is to do a new boards manager release. See [https://github.com/MCUdude/MegaCore/commit/3d61fc2fe1fcce22daf8c46b70e4c8cd6e10e1c7](https://github.com/MCUdude/MegaCore/commit/3d61fc2fe1fcce22daf8c46b70e4c8cd6e10e1c7)

**Comment by MarphXL** [comment]
in your pinout num digital pins are 84. why not 86?

**Comment by MCUdude** [comment]
Well, that's a bug. It's supposed to be 86.
