### ISSUE TITLE
Pin mapping for the Atmega 1284p?

### ISSUE THREAD

**Issue by mrdesignr** [MCUdude/MegaCore#116]
Could you kindly provide a document to help me with this? I remember acquiring one from another site which referenced this site but my hard drive fried and having trouble retrieving this. I did use MegaCore to burn my 1284 successfully.

**Comment by per1234** [comment]
For ATmega1284P, you're on the wrong repository.

You want MightyCore:
https://github.com/MCUdude/MightyCore
Which does provide pin mapping diagrams:
https://github.com/MCUdude/MightyCore#pinout

**Comment by mrdesignr** [comment]
Thank you. You may close this issue or leave it open for others.

**Comment by per1234** [comment]
You're welcome. Please close it.
