### ISSUE TITLE
Wiring implementation - portWrite

### ISSUE THREAD

**Issue by duraiyuvaraj** [MCUdude/MegaCore#117]
I tried to check/test ATMEGA1281 PortG (6 bit Port) portWrite() as Port G bit 6 and 7 are read only as per the datasheet. Compiled without error. Further testing reveals even the below code compiles without any error

```c
byte portNumber = 20; // Use port B
byte val = 0;

void setup() {
  portMode(portNumber, OUTPUT);
}

void loop() {
  portWrite(portNumber, val);
  val = val + 1;
  if (val > 255)
    val = 0;
}
```

**Comment by MCUdude** [comment]
Well, it's not a bug. `digitalWrite(255, HIGH)` also compiles without any errors or warnings. It's very difficult to catch this at compile time. Bottom line; the user has to know the limitations of the hardware they're working with.
