### ISSUE TITLE
Fusebit setting ATMega 128

### ISSUE THREAD

**Issue by umarmaajid** [MCUdude/MegaCore#121]
can you help me, setting fuse bit ATMega 128 16AU
![eror2](https://user-images.githubusercontent.com/6671264/69598509-1be07b00-103c-11ea-9b55-d172aabfcada.png)

**Comment by MCUdude** [comment]
A closer look at the screenshot reveals that you're using a USBtinyISP programmer. This has a particular bug that Avrdude is not able to verify the flash content above 64kB. However, it does work. If you're worried about this error you will have to use a different programmer such as the USBasp.
