### ISSUE TITLE
millis() cannot work if using timer interrupt

### ISSUE THREAD

**Issue by killer890** [MCUdude/MegaCore#122]
anyone can help,,if i use timer1 or timer2 for intterupt some function not work like millis(), Serial.readString(), ect

**Comment by MCUdude** [comment]
Can you post your code, please? If not, there's no way I can investigate this.

**Comment by killer890** [comment]
Thank's for the replay...after i search i find the problem...and it solve

**Comment by MCUdude** [comment]
Great to hear you figured it out!
