### ISSUE TITLE
Option for External Clock rather than an External Crystal

### ISSUE THREAD

**Issue by ilium007** [MCUdude/MegaCore#123]
How difficult would it be to get an option to run an external clock instead of a crystal?

CKSEL3:0 need to be set to 0000

**Comment by MCUdude** [comment]
If you want to use an external clock rather than a crystal, all you have to do is to connect your clock signal to the XTAL1 pin. Just leave the XTAL2 pin unused 🙂

However, if you absolutely want to set all CKSEL bits to zero, you can always modify boards.txt.
