### ISSUE TITLE
received NACK on transmit of address

### ISSUE THREAD

**Issue by LeonRonin** [MCUdude/MegaCore#124]
hi
i'm trying to communicate with a mpu6050 breakout board using an atmega128A but I get "received NACK on transmit of address" on Wire.endTransmission(). I can't seem to find the source of the problem. Could you please help me??

**Comment by MCUdude** [comment]
Can you find the MPU6050 when running the i2c_scanner sketch?

**Comment by LeonRonin** [comment]
it's ok. I traced the problem to the pcb itself. great job by the way! we really appreciate it
