### ISSUE TITLE
wake up      ISR(INT2_vect)

### ISSUE THREAD

**Issue by AnatiliyKsl** [MCUdude/MegaCore#125]
Hi
Atmega64A ,Arduino IDE 1.6.9 ,MegaCore

I need to go to sleep and wake up with interrupt 2

```c
#include <Arduino.h>
#include <avr/sleep.h>
#include <avr/interrupt.h>

#define KEY_1 20
#define LED_RED 13

//*******************************************************************
#ifndef cbi
#define cbi(sfr, bit) (_SFR_BYTE(sfr) &= ~_BV(bit))
#endif
#ifndef sbi
#define sbi(sfr, bit) (_SFR_BYTE(sfr) |= _BV(bit))
#endif
//*********************************************************************
void setup()
 {
 pinMode(KEY_1, INPUT);//PD2 20 INT 2
 pinMode(LED_RED, OUTPUT);
digitalWrite(LED_RED,HIGH);//off led
sleepMode(SLEEP_POWER_DOWN);
sei();
}
void loop() {
delay(1000);
 attachInterrupt(2, slOut,HIGH);
sleep(); 
//---------
 sleep_disable();

while(PIND & (1 << PD2)){ cbi(PORTB,5);delay(50);sbi(PORTB,5);delay(50);}//отпускание клавиши
}
void slOut()
{ 
  detachInterrupt(2);
  sleep_disable();
}
 ```

Goes to sleep  - sleep(); CURRENT CONSUMPTION 0.7mA
but the interrupt does not work, when a high level is applied to the pin PD2, it does not go out of sleep
if after  attachInterrupt(2, slOut,HIGH);
 insert set edge interrupt from  INT2
    EICRA=0B00110000;
    EIMSK = 0B00000100;
out of sleep
but interruption does not turn off

if after  detachInterrupt(2);
 insert
 EIFR=0B11111111;
  EIMSK = 0 ;  

WHY IS THAT ???

**Comment by MCUdude** [comment]
Read issue #97.

**Comment by AnatiliyKsl** [comment]
thanks
but this does not completely solve the problem
as I need to disconnect interrupt from INT 2 
question
why the error is generated when applying the expression:
ISR(INT2_vect)
WInterrupts.c.o (symbol from plugin): In function `attachInterrupt':

(.text+0x0): multiple definition of `__vector_3'

sketch\sl3last.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

collect2.exe: error: ld returned 1 exit status

exit status 1
Ошибка компиляции для платы ATmega64.

**Comment by MCUdude** [comment]
Please post your code that generates this error message. If you're using attachInterrupt with INT2, you can't use ISR(INT2_vect) too. You will have to choose; either use attachInterrupt, or setup INT2 interrupt manually.
