### ISSUE TITLE
Edit Bootlader (MEGA2560) for programming, regardless of one of the 3 serial.

### ISSUE THREAD

**Issue by sergioxdev** [MCUdude/MegaCore#128]
Hi Guys
I have a mega2560, I would like to enable programming on the 3 UART0, UART1 or UART2

so that we can load our program, regardless of one of the 3.

I have read a lot of documentation, I have tried but I cannot.
maybe it will be me, or maybe it's not feasible, someone has already faced this problem.

**Comment by MCUdude** [comment]
As far as I know, that is not possible. You can, however, ask at the [official Optiboot repo](https://github.com/Optiboot/optiboot).
