### ISSUE TITLE
upload sketch (my code) to atmega64

### ISSUE THREAD

**Issue by ntsang-lab** [MCUdude/MegaCore#139]
thanks sir MCUdude,
tomaskovacik and @ per1234 helped me to fix the bootloader problem .Also no problem to upload sketch without bootlader at ISP mode (with holding shift key).
I want to upload code with TX, RX pins to use function '"SERIAL MONITOR" in arduino IDE.
I use my arduino uno (which is a DIP chip) I removed the atmeaga 328p from the board, and made the connection like this:

my arduino (removed atmega328p) -atmega64
5v-5v
gnd-gnd
TX-TX
RX-RX 
RESET - RESET (go through the 100nF cap)
 After connecting as above, I upload the code to atmeaga64, it fails (Ctl + U)
i have tried changing TX and RX

**Comment by MCUdude** [comment]
You will have to install the bootloader first before you can upload using a USB to serial adapter. Also, if you're using the pins on an Arduino UNO, it already has a 100nF capacitor on the reset line. I don't think you'll need it.
