### ISSUE TITLE
Arduino ide atmega 128 uart troubles with uart0 

### ISSUE THREAD

**Issue by punxer** [MCUdude/MegaCore#141]
https://mysku.ru/blog/aliexpress/45768.html - this is schematics
https://gist.github.com/ircphp/b25f979855252b0e630c this is code 
This code with redefined io pins baud 9800, spi and sd card works good, delays work good with 1 and 8 mhz internal rc, with external rc 8mhz and 16 mhz all code doesnt work properly, used 1111 in cksel and 0 and 1 in ckopt. But i receive bad nmea strings from uart .8n1 settings. I defined fcpu with needed freq. Gps are sending nmea strings every second with 9600 and 8n1, i can read gps strings at pc with this settings . There is no bootloader at mega 128, tryed alot of fuses combination at 1 and 8 internal rc. Thanx in advance . 
Andrey  Punxer@yandex.ru

**Comment by MCUdude** [comment]
Sorry for the late reply. There is no reason why it shouldn't work with an external oscillator. The fuse settings in Arduino IDE should be sufficient. You should not have to manually define F_CPU. Note that you'll have to select your oscillator option under the Tools menu in Arduino IDE for the code to work properly.

Do you have a frequency counter or an oscilloscope you can use to measure the frequency of the external oscillator? Seems to me like it is either too slow or too fast. It would also be great if you could measure how long delay(1) and delay(1000) actually last to get an impression on how bad timing really is.

**Comment by MCUdude** [comment]
I'm closing this issue due to no response from OP.
