### ISSUE TITLE
limitations of atmega64

### ISSUE THREAD

**Issue by ntsang-lab** [MCUdude/MegaCore#149]
Thanks for your sharing
I have done successfully following your tutorial with atmega64 / 128.
but i just stopped at control on / off the pins.
I have a question, can I fully utilize timer, servo, interrupt ... functions and use other functions like on arduino uno with your bootloader?
And if it has limited scripting, and functionality compared to arduino uno, please let me know in advance so that future board designs may change
Thanks

**Comment by MCUdude** [comment]
> I have a question, can I fully utilize timer, servo, interrupt ... functions and use other functions like on arduino uno with your bootloader?

The bootloader has nothing to do with the user application. Its job is to load new firmware, nothing else. You can fully utilize all peripherals on the ATmega64/128, just like on all AVRs, including the Arduino UNO. However, some registers may have slightly different names and functionality. Read the datasheet to get everything right.
