### ISSUE TITLE
AT90CAN128 stucked in Wire.endTransmission()

### ISSUE THREAD

**Issue by sebashb** [MCUdude/MegaCore#151]
Hi,

I'm trying to use the AT90CAN128 to read data from a INA226 with peterus/INA226Lib library but my code is getting blocked in the `ina.configure()` more precisely in the `writeRegister16(INA226_REG_CONFIG, config);` `Wire.endTransmission();` call. I have checked `twi.c` and chip is blocked in the while in line 277:

```
// wait for write operation to complete
  while(wait && (TWI_MTX == twi_state)){
    continue;
  }
```

The library should not be the problem since I have already used it before with a Teensy 3.2.

I'm using the Simple.ino example of the library, and I have already checked my connection between the INA and the AT90. Schematic is below:

![Schematic](https://user-images.githubusercontent.com/12198921/103424638-5a345c00-4ba5-11eb-8c4c-54fe72b38644.png)

<img width="266" alt="image" src="https://user-images.githubusercontent.com/12198921/103468441-de771280-4d50-11eb-9724-fd61f8bed5fb.png">

PS: Pull-up resistors on I2C bus are 10 kΩ on the  PCB.

**Comment by sebashb** [comment]
@MCUdude  I have just tried the example `MegaCore/avr/libraries/Wire/examples/i2c_scanner/` and the same thing happened, the AT90CAN128 gets sucked on the `Wire.endTransmission();` have you tried I2C before on this chip?

**Comment by MCUdude** [comment]
I just hooked up an i2c LCD 1602 driver, and I'm able to "ping" the i2c bus with an AT90CAN128. Note that `Wire` is blocking, so the program will hang if either the SDA or SCL line is held low.

Output:
```
I2C Scanner
Scanning...
I2C device found at address 0x20  !
done

Scanning...
I2C device found at address 0x20  !
done

Scanning...
I2C device found at address 0x20  !
done

...
```

**Comment by sebashb** [comment]
Hi MCUdude, meanwhile I have desolder the INA226 and I was also able to ping the I2C bus but since I had no devices on the bus I have not closed this issue. I will test with a new INA during this week.

**Comment by sebashb** [comment]
I have had the opportunity to solder a new INA226 to the PCB and now it's working the way it should. Sorry for the trouble.
