### ISSUE TITLE
I cannot compile

### ISSUE THREAD

**Issue by vanduy10061991** [MCUdude/MegaCore#152]
![2021-01-11_083808](https://user-images.githubusercontent.com/19367345/104141339-b5a5eb80-53e8-11eb-9423-ae41918a7d2a.jpg)

**Comment by mohei9aldeen** [comment]
hello @vanduy10061991 
did you solve your issue ?

**Comment by mcuee** [comment]
Usually this means Arduino installation problems.

**Comment by MCUdude** [comment]
When searching for `Arduino "exec: “cmd”: executable file not found in %PATH%"`, I get lots of results and several solutions that have worked for other users. It's a Windows/Arduino IDE related issue.
