### ISSUE TITLE
copy_flash_pages

### ISSUE THREAD

**Issue by admindotnu** [MCUdude/MegaCore#154]
Quick question, and googling for some time now without finding a proper yes or no.

Is in the current megacore support for copy_flash_pages. And for current i mean installing the boards through boardmanager and without compiling myself.

Thank you !

**Comment by MCUdude** [comment]
Hi! The pre-compiled Optiboot flash bootloaders do not support copy_flash_pages by default. for this, you'll have to compile your own bootloader.

**Comment by MCUdude** [comment]
Ignore the message above. All targets with 64kB flash or more support copy_flash_pages by default. Sorry for not being clear, I had to look in the source code to be sure!

**Comment by admindotnu** [comment]
Thank you for quick reply! 

I am going to dig deeper why me fetched bin is not applied.

**Comment by jandrassy** [comment]
@MCUdude Hans, makeall doesn't have COPY_FLASH_PAGES=1 for any MCU

**Comment by MCUdude** [comment]
Sorry, I got it wrong, @jandrassy is right.

**Comment by jandrassy** [comment]
@admindotnu, for which board you want Optiboot with my copy_flash_pages function?
