### ISSUE TITLE
i have this error

### ISSUE THREAD

**Issue by fadi0albaghdadi** [MCUdude/MegaCore#167]
Low memory available, stability problems may occur.
Does it affect the processor? atmega128

**Comment by lshw** [comment]
The stack length may be insufficient.

**Comment by tomaskovacik** [comment]
This is problem with your code not core. You must use micro with more ram or optimise yout code. Anyway we need more informations about your hw setup and your code

**Comment by fadi0albaghdadi** [comment]
> The stack length may be insufficient.

Does this affect the operation of the processor?

**Comment by fadi0albaghdadi** [comment]
> This is problem with your code not core. You must use micro with more ram or optimise yout code. Anyway we need more informations about your hw setup and your code

Does this affect the operation of the processor?

**Comment by tomaskovacik** [comment]
50:50 chance

- try it
- google warning message and read what was already witen elsewhere
- we can help you only if you post your code here

**Comment by fadi0albaghdadi** [comment]
> 50:50 chance
> 
> * try it
> * google warning message and read what was already witen elsewhere
> * we can help you only if you post your code here

The code is very private, it cannot be published and is too large

**Comment by tomaskovacik** [comment]
Then you must simply test it

**Comment by MCUdude** [comment]
Optimize your code to use less RAM, or choose a larger, pin compatible microcontroller with more RAM such as the Atmega1281 or ATmega2561.

**Comment by fadi0albaghdadi** [comment]
Does that mean I can replace the atmega128 processor with atmega1281

**Comment by MCUdude** [comment]
Yes, as long as your hardware setup doesn't depend on anything unique to the ATmega128.

**Comment by lshw** [comment]
use  F(string) to put string into ROM.

Serial.println("hello"); // use 5 byte ram,
Serial.println(F("hello")); // use 0 byte ram

F(string)   can save a lot of ram.
