### ISSUE TITLE
Mega2560 programming megacore avrdude: Device signature = 0x000000

### ISSUE THREAD

**Issue by ThomHehl** [MCUdude/MegaCore#168]
I am getting this issue when programming the megacore as bootloader from another Mega2560.

**Comment by MCUdude** [comment]
The programmer can't communicate with the target chip

**Comment by ThomHehl** [comment]
Thank you. Found the problem and posted to stack exchange: https://arduino.stackexchange.com/questions/84879/loading-code-to-a-mega-2560. Closing this issue.
