### ISSUE TITLE
Extended SRAM

### ISSUE THREAD

**Issue by r4wabr** [MCUdude/MegaCore#169]
Hi.  How about make  options for build projects with use of Extended SRAM?

**Comment by MCUdude** [comment]
I'm not sure, I've never used external ram with AVRs. I would probably use PlatformIO for something like this, since it gives you much you can configure in your build setup.

This might be relevant:
https://scienceprog.com/adding-external-memory-to-atmega128/

**Comment by MCUdude** [comment]
I'm closing this issue because it's not really an issue related to MegaCore. If you need further assistance regarding external RAM; I suggest you ask over at the Avrfreaks forum. They know a whole lot more about this than me.
