### ISSUE TITLE
delay() function 

### ISSUE THREAD

**Issue by leventesen** [MCUdude/MegaCore#17]
When I call delay(100000UL) function it waits only 1 second.
_delay_ms() function does not have problem.
This issue is not tested in real hardware enviroment, it occurs in Proteus simulation.

**Comment by MCUdude** [comment]
Try with real hardware, and try removing the UL suffix. If the problem still occurs you should create an issue at [Arduino's repository](https://github.com/arduino/Arduino), as it's they code (i haven't done any modifications to the delay fiction)

**Comment by leventesen** [comment]
I changed the implementation of delay(ms) function and for now it's working. I also created a topic in Arduino mailing group about this issue and waiting for approve. I will inform you about this.
Thanks.
