### ISSUE TITLE
Need a Bootloader for ATmega2561 working on 12.500 MHz

### ISSUE THREAD

**Issue by miksumin** [MCUdude/MegaCore#173]
I am using MegaCore with ATMega2561 working on External 12.500 MHz frequency but there is no Optiboot bootloader for it. Can you please build it for me?

**Comment by MCUdude** [comment]
It's all there. Build it yourself, it's a good learning experience

**Comment by miksumin** [comment]
I don't have 'make' package

**Comment by miksumin** [comment]
There is no ..\..\..\tools\avr\utils\bin\make

**Comment by miksumin** [comment]
Please help

**Comment by miksumin** [comment]
make atmega2561 AVR_FREQ=12500000L BAUD_RATE=115200 LED=G0 LED_START_FLASHES=2 UART=0/1

**Comment by MCUdude** [comment]
A baud rate of 115200 at 12.5 MHz wouldn't work at all. Too much error. Look at the U2X=1 field, that's what the bootloader uses. Choose a green baud rate instead.

<img width="1010" alt="Skjermbilde 2021-07-30 kl  19 59 34" src="https://user-images.githubusercontent.com/3238730/127693546-c3816a6f-8d48-4d6b-824a-4e4b7369fa95.png">

**Comment by miksumin** [comment]
Ok, I hope 57600 would be ok. So let's use the following:
make atmega2561 AVR_FREQ=12500000L BAUD_RATE=57600 LED=G0 LED_START_FLASHES=2 UART=0/1

**Comment by MCUdude** [comment]
OK, here you go.

[12500000L.zip](https://github.com/MCUdude/MegaCore/files/6909342/12500000L.zip)

**Comment by miksumin** [comment]
Many thanks
