### ISSUE TITLE
Using copy_flash_pages

### ISSUE THREAD

**Issue by rkertesz** [MCUdude/MegaCore#175]
Are there any basic examples or instructions on how to use copy_flash_pages to receive a hex over uart from another device ( like another Arduino) or from an ftp server and then write the new firmware to the boot section?

Is this already available in bigboot?

**Comment by jandrassy** [comment]
https://github.com/jandrassy/ArduinoOTA/blob/master/examples/Advanced/OTASketchDownload/OTASketchDownload.ino
only you will read the binary from Serial, not from WiFiClient

**Comment by rkertesz** [comment]
I see this statement in the comments at the top of the example but didn't find any instructions in the readme. is there something I need to do to the hex file?

>  To create a bin file for AVR boards see the instructions in README.MD.

**Comment by jandrassy** [comment]
>To use remote upload from IDE with SDStorage or InternalStorage, copy platform.local.txt from extras/avr folder, next to platform.txt in the boards package used (Arduino-avr or MCUdude packages). 

the configuration files setup creation of a bin file
