### ISSUE TITLE
make wire library non-blocking

### ISSUE THREAD

**Issue by imanfreeman** [MCUdude/MegaCore#179]
Hi @MCUdude 
first, I would like to thank you for your great job. It's really appreciated.
then, I want to mention a problem in the Wire library which results in a freezing code!
the Arduino Wire library has been updated to address this problem by defining a timeout function.
It would be very great if you can add this update to the Mega (and probably mini) core as well.
regards

**Comment by MCUdude** [comment]
The Wire library does now support timeouts. However, it needs to be enabled in the source code:

https://github.com/MCUdude/MegaCore/blob/c87824f5733765da0c5fc410d8cd3af1791371d0/avr/libraries/Wire/src/Wire_timeout.h#L1-L6
