### ISSUE TITLE
can't compile megaCore Example codes

### ISSUE THREAD

**Issue by mohei9aldeen** [MCUdude/MegaCore#181]
exec: "cmd": executable file not found in %PATH%
Error compiling for board ATmega128.

**Comment by MCUdude** [comment]
Have you installed Arduino IDE from the Microsoft store? 
If yes, uninstall this version and download Arduino IDE 1.8.19 from [arduino.cc](https://www.arduino.cc/en/software).

**Comment by MCUdude** [comment]
> Have you installed Arduino IDE from the Microsoft store?

Probably.
