### ISSUE TITLE
"Burn Bootloader" that can only be used once

### ISSUE THREAD

**Issue by 13507086298** [MCUdude/MegaCore#182]
I write the Atmega128 via "Burn Bootloader" and it works fine, but after I upload the sketch once via UART1, the Bootloader doesn't work anymore, which means "Burn Bootloader" is a one-off in my actual use. I would like to know how to keep the "Burn Bootloader". Allows me to upload sketches via UART1 each time
![image](https://user-images.githubusercontent.com/73020592/164972052-7cc4deca-a4ed-4c8f-aa23-d7530284d2fe.png)
![image](https://user-images.githubusercontent.com/73020592/164972076-e26ca178-47ed-4327-b1ce-198f46254237.png)
![image](https://user-images.githubusercontent.com/73020592/164972097-8f44ba44-0b4f-47ec-afeb-42e670dcf9eb.png)
![image](https://user-images.githubusercontent.com/73020592/164972165-01bf1962-f084-4fbd-bfdf-ac929e05c253.png)
But I will go up the grass map again, there will be an error.
![image](https://user-images.githubusercontent.com/73020592/164972271-5c15f88f-658e-4260-a9cd-aaf385440e3c.png)
This indicates that Bootloader has failed. I can make UART1 get the sketch through UART1 by using Tools-> Burn Bootloader, and it will fail again after success.

**Comment by tomaskovacik** [comment]
did you implemented auto-reset circuit?

**Comment by 13507086298** [comment]
@tomaskovacik  Thank you very much for your reminder, I have an Auto-reset circuit, but it doesn't seem to work, I can upload normally after I reset it manually, I will check my hardware circuit. thank you very much
