### ISSUE TITLE
Is there support for the ATmega128RFA1 processor [question]

### ISSUE THREAD

**Issue by mrWheel** [MCUdude/MegaCore#185]
Is there any change of support for the ATmega128RFA1 mcu and than specifically the RF part.

Do you have knowledge of any library that does?

**Comment by MCUdude** [comment]
Hi!

MegaCore does not support ATmega128RFA1. Even though it _appears_ to have much in common with the ATmega128, it's a completely different chip with different peripherals and pinout. Adding support for this is not a priority, sorry.

I don't know if there exists Arduino support for this at all. However, you can always use Microchip Studio or MPLAB X.
