### ISSUE TITLE
Original Arduino Mega2560 bootloader isssues with EEPROM read

### ISSUE THREAD

**Issue by mcuee** [MCUdude/MegaCore#187]
I believe this is still relevant and it will be good to merge the following fix.
* https://github.com/arduino/ArduinoCore-avr/pull/24

**Comment by mcuee** [comment]
Referece from avrdude.
* https://github.com/avrdudes/avrdude/issues/515

**Comment by MCUdude** [comment]
Thanks for the links! I'll apply the fix, re-compile and test the new binaries before releasing a new boards manager version of MegaCore. Thanks for looking into all these issues @ mcuee !
