### ISSUE TITLE
To adopt urboot for MegaCore

### ISSUE THREAD

**Issue by mcuee** [MCUdude/MegaCore#202]
urboot offers quite some advantages over the existing Optiboot and stk500v2 bootloader in MegaCore.

It will be great to offer urboot in MegaCore.

**Comment by MCUdude** [comment]
MegaCore, MightyCore, MiniCore, MajorCore, and MicroCore have now adopted Urboot.
Thank you for developing this excellent bootloader @stefanrueger! Now let the mass testing begin...

**Comment by stefanrueger** [comment]
@MCUdude How cool is that! Thanks for supporting the idea! I am curious as to how this will work out!
