### ISSUE TITLE
ArduinoOTA problems on Mega2560 using Megacore >= 3

### ISSUE THREAD

**Issue by jegjessing** [MCUdude/MegaCore#212]
Hi. I have this very simple program. It works fine if I burn the bootloader with from MegaCore 2.2.x.
But, if I burn the bootloader from MegaCore 3.x (urboot) then it never gets to "Done", it keeps rebooting and keeps printing "Mjello"

Is there some ArduinoOTA/urboot issue I'm not aware of?

```#define NO_OTA_NETWORK
#include <ArduinoOTA.h>

void setup() {
  Serial.begin(115200);
  while (!Serial);
  delay(500);
  Serial.println("Mjello");
  
}

boolean done = false;
void handleDownload()
{
  byte b;
  if (done) return;

  b = 12;
  InternalStorage.open(70002);
  delay(1000L);
  InternalStorage.write(b);
  Serial.println("Done");
  
  done = true;
}

void loop() {
  // put your main code here, to run repeatedly:
  handleDownload();

}
```

Thanks in advance

**Comment by MCUdude** [comment]
The ArduinoOTA project has not been updated to support Urboot yet. There's not much I can do about this, but maybe the ArduinoOTA developers will look into it. Meanwhile, you'll have to use MegaCore v2

**Comment by jegjessing** [comment]
Thanks for a quick and precise answer
