### ISSUE TITLE
Is ATMegaS128 supported?

### ISSUE THREAD

**Issue by Samskandar** [MCUdude/MegaCore#25]
Will I be able to use the MegaCORE in Arduino IDE for the ATMegaS128? Noob here, worried about ATMegaS128 running off 3.3V instead of ATMega128's 5.0V. I intend to attach a 8MHz with your MegaCORE minimal setup wiring. Thanks for the help! Pls delete this thread if i posted in the wrong place.

**Comment by MCUdude** [comment]
Yup, I'm 90% sure. It seems like the ATmegaS128 has the same device signature as the ATmega128, so you can just use the core without any modifications. Just connect an 8 MHz crystal to it, select the "8 MHz external" option, and burn the bootloader.
