### ISSUE TITLE
Timers of Atmega128

### ISSUE THREAD

**Issue by DallySon** [MCUdude/MegaCore#44]
I have a new problem.
I try to use TimerOne lib.
It's perfectly working with Atmega328 (as SnoozeLib). But I have a next Errors on MegaCore: 
"was not declared in this scope" for regiters TIMSK1, GTCCR and for PSRSYNC.
If I change TIMSK1->TIMSK - it accepted by compiler. (but I understand that it is no right way).

My goal is to use your sleep() and noSlip() with timer interrupt and hardware interrupt for wakeUp of CPU.
Help me please what I have todo for it.

or may be You can to recommend some onother sleep/timer library what will compitable with MegaCore.

Thanks so much.

**Comment by MCUdude** [comment]
You probably have to add this to the `known_16bit_timers.h` file:

``` c++
#elif defined(__AVR_ATmega64__) || defined(__AVR_ATmega128__)
  #define TIMER1_A_PIN   13
  #define TIMER1_B_PIN   14
  #define TIMER1_C_PIN   15
  #define TIMER1_ICP_PIN 22
  #define TIMER1_CLK_PIN 23
```

However, this issue is not related to MegaCore in any way; the library is not made for the ATmega64/128. I suggest you create an issue over at the library repo so the author can fix it permanently
