### ISSUE TITLE
Software Serial doesnt work

### ISSUE THREAD

**Issue by Sanket-Drake** [MCUdude/MegaCore#5]
Any existing library that can help with using Software serial on this board ?

**Comment by MCUdude** [comment]
I don't think so. Does there exist a SoftSerial library that take us to of the hardware interrupts? The ATmega64/128 got 8 interrupt pins, so there's plenty if you find a library 



3. jun. 2016, 14:57 kl. 14:57 skrev Sanket-Drake <notifications@github.com>:

**Comment by MCUdude** [comment]
This is somewhat complicated, since the ATmega64/128 doesn't got PCINTs. Have a look at [this](http://forum.arduino.cc/index.php?topic=404841.0) post. I think this is your best shot 😃
