### ISSUE TITLE
I2C pind don't match Datasheet

### ISSUE THREAD

**Issue by WD24** [MCUdude/MegaCore#54]
Hi I've only looked at your arduino pin map for the 64 pin avr. I've noticed that the pins for the I2C communication don't match the data sheet.

MegaCore/avr/variants/64-pin-avr/pins_arduino.h

lines 79 & 80

static const uint8_t SDA = 18;
static const uint8_t SCL = 19;

i think should read 

static const uint8_t SDA = 19;
static const uint8_t SCL = 18;

**Comment by MCUdude** [comment]
Thanks for reporting! Just pushed a fix
