### ISSUE TITLE
ATmega64 issue

### ISSUE THREAD

**Issue by 125401qwerty** [MCUdude/MegaCore#90]
Hi, 

I try to write the bootloader to Atmega64.
As a programmer I use Arduino Nano with ArduinoISP sketch.

I get this error:
avrdude: Device signature = 0xff8000
avrdude: Expected signature for ATmega64 is 1E 96 02
         Double check chip, or use -F to override this check.

I checked the connections many times. I tried to write the bootloader to another Arduino nano, everything happens as it should, while keeping the reset.

**Comment by 125401qwerty** [comment]
The problem is solved. Just soldered the wires to the programmer.

**Comment by MCUdude** [comment]
Great! An incorrect decive signature is almost always caused by a hardware issue
