### ISSUE TITLE
atmega 64a

### ISSUE THREAD

**Issue by anandspathak** [MCUdude/MegaCore#94]
Sir MCUdude,
Is there any difference between atmega 64 and 64a?
Do the above have different bootloader respectively?
I m new to this so pls help..
Regards
Anand Pathak

**Comment by MCUdude** [comment]
Hi!
No, there's no difference between the ATmega64 and the ATmega64A in terms of code compatibility.

If you want to read about the electrical differences you can read the [AVR524](http://ww1.microchip.com/downloads/en/AppNotes/doc8165.pdf) document.

**Comment by anandspathak** [comment]
thanks sir, i uploaded bootloader successfully to atmega 64a... having some issue to blink an led,

**Comment by anandspathak** [comment]
update.....blinking done...experimenting ahead

**Comment by anandspathak** [comment]
Thanks for this wonderful core...its up and running on atmega 64a(once I left hope of which)
