### ISSUE TITLE
atmega 64a crystal issue

### ISSUE THREAD

**Issue by anandspathak** [MCUdude/MegaCore#95]
Sir MCUdude,
i have atmega 64a with megacore running excellent at 8mhz crystal external and internal both...
but 16 mhz and 20 mhz crystals are not working and getting error as below upon bootloading...
can u suggest something...
Regards
Anand Pathak

***************************************************************
Arduino: 1.8.7 (Windows 7), Board: "ATmega64, 2.7v, Disabled (default), 16 MHz external"

C:\Program Files\Arduino\hardware\tools\avr/bin/avrdude -CC:\Users\vrindavan\AppData\Local\Arduino15\packages\MegaCore\hardware\avr\2.0.1/avrdude.conf -v -patmega64 -cstk500v1 -PCOM3 -b19200 -e -Ulock:w:0x3f:m -Uefuse:w:0xff:m -Uhfuse:w:0xc6:m -Ulfuse:w:0b10111111:m 

avrdude: Version 6.3-20171130
         Copyright (c) 2000-2005 Brian Dean, http://www.bdmicro.com/
         Copyright (c) 2007-2014 Joerg Wunsch

         System wide configuration file is "C:\Users\vrindavan\AppData\Local\Arduino15\packages\MegaCore\hardware\avr\2.0.1/avrdude.conf"

         Using Port                    : COM3
         Using Programmer              : stk500v1
         Overriding Baud Rate          : 19200
         AVR Part                      : ATmega64
         Chip Erase delay              : 9000 us
         PAGEL                         : PD7
         BS2                           : PA0
         RESET disposition             : dedicated
         RETRY pulse                   : SCK
         serial program mode           : yes
         parallel program mode         : yes
         Timeout                       : 200
         StabDelay                     : 100
         CmdexeDelay                   : 25
         SyncLoops                     : 32
         ByteDelay                     : 0
         PollIndex                     : 3
         PollValue                     : 0x53
         Memory Detail                 :

                                  Block Poll               Page                       Polled
           Memory Type Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
           ----------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
           eeprom         4    20    64    0 no       2048    8      0  9000  9000 0xff 0xff
           flash         33     6   128    0 yes     65536  256    256  4500  4500 0xff 0xff
           lfuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           hfuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           efuse          0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           lock           0     0     0    0 no          1    0      0  9000  9000 0x00 0x00
           calibration    0     0     0    0 no          4    0      0     0     0 0x00 0x00
           signature      0     0     0    0 no          3    0      0     0     0 0x00 0x00

         Programmer Type : STK500
         Description     : Atmel STK500 Version 1.x firmware
         Hardware Version: 2
         Firmware Version: 1.18
         Topcard         : Unknown
         Vtarget         : 0.0 V
         Varef           : 0.0 V
         Oscillator      : Off
         SCK period      : 0.1 us

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.02s

avrdude: Device signature = 0x000000 (retrying)

Reading | ################################################## | 100% 0.02s

avrdude: Device signature = 0x000000 (retrying)

Error while burning bootloader.
Reading | ################################################## | 100% 0.02s

avrdude: Device signature = 0x000000
avrdude: Yikes!  Invalid device signature.
         Double check connections and try again, or use -F to override
         this check.

avrdude done.  Thank you.

**Comment by MCUdude** [comment]
Hi!
It's very likely a hardware issue. A device signature of 0x000000 indicated no communication with the microcontroller. Try using another crystal, try replacing the capacitors that's connected to the crystal with some other value. You can try 10pF, 18pF, 22pF and 27pF. Also try to move the crystal closer to the microcontroller itself. Long crystal traces is often a problem

**Comment by anandspathak** [comment]
Thanks for reply...
I'll do as per your suggestion and revert back...
Regards

**Comment by anandspathak** [comment]
Sir is this atmega64a designed to work only at 8 mhz not more than that? 
I am using breadboard...using 8mhz crystal I can do everything. ..when I replace higher frequency crystal leaving everything as it is, the above error occurs...just clearing...

**Comment by MCUdude** [comment]
Sorry, I though you used an ATmega128. Where did you buy your ATmega64A? I've actually receved microcontrollers from china where the microcontroller actually is refurbished. The "new" text did say ATmega32A, but they didn't sand the chip properly. If you had the light correct I could barely spot "ATmega32L". This _might_ have happend to you as well I guess.

**Comment by MCUdude** [comment]
The ATmega64A should infact support 16MHz. Buy how are you able to breadboard this? Do you have some kind of breakout board?

**Comment by anandspathak** [comment]
Sir I made a simple pcb of atmega 64a for breadboard...ill show you image when I am back at home...
I got atmega 64a from aliexpress and I belong to india...

**Comment by MCUdude** [comment]
Great! Please post some high-res photos when you're back from work 👍

**Comment by anandspathak** [comment]
Ya sure

**Comment by anandspathak** [comment]
Sir MCUdude,
Sorry for being late,
here are your images,
though the pcb is homemade by me but still works without any issues...

![20181102_005501](https://user-images.githubusercontent.com/43384018/47874828-e5d1c700-de3a-11e8-8a43-c2d1f1ba53b9.jpg)
![20181102_005529](https://user-images.githubusercontent.com/43384018/47874829-e5d1c700-de3a-11e8-8fcc-bbde075f6a2d.jpg)
![20181102_005548](https://user-images.githubusercontent.com/43384018/47874830-e66a5d80-de3a-11e8-8f90-3087e8933cdb.jpg)
![20181102_005615](https://user-images.githubusercontent.com/43384018/47874833-e702f400-de3a-11e8-8bf2-a2a87c98f5ea.jpg)
![20181102_005631](https://user-images.githubusercontent.com/43384018/47874835-e702f400-de3a-11e8-9705-6048e3789792.jpg)
![20181102_005645](https://user-images.githubusercontent.com/43384018/47874837-e79b8a80-de3a-11e8-9e7f-ce204342522b.jpg)

**Comment by aasimmerchant05** [comment]
Dear Sir Where have u connected the crystal? There is no internal oscillator running at 16MHz. You need an external crystal for that

**Comment by MCUdude** [comment]
I suggest you take this at the Arduino forum or the Avrfreak forum. This is a hardware issue, and nothing to do with MegaCore really.
