### ISSUE TITLE
Improve pinout image

### ISSUE THREAD

**Issue by rafacouto** [MCUdude/MegaCore#99]
In the [Atmega128 pinout image](https://camo.githubusercontent.com/02359aa02f9ff86bba528efac949864febf50d2a/687474703a2f2f692e696d6775722e636f6d2f657a354d7976492e6a7067), it'd be convenient to indicate PDI and PDO pins with PE0 and PE1 respectively. It is important to indicate where to connect in order to program the MCU via SPI (I have lost some time investigating the cause of not loading the firmware through MISO/MOSI pins, and it seems a common trap after reading some forums).

Thanks for your job!

**Comment by MCUdude** [comment]
Thanks for the heads-up!
